<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="2" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="120423" started-at="2018-10-17T06:32:00Z" finished-at="2018-10-17T06:34:01Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="120423" started-at="2018-10-17T06:32:00Z" finished-at="2018-10-17T06:34:01Z">
      <class name="testcases.TC001">
        <test-method status="PASS" signature="initiateSuite()[pri:0, instance:testcases.TC001@23faf8f2]" name="initiateSuite" is-config="true" duration-ms="1325" started-at="2018-10-17T06:31:59Z" finished-at="2018-10-17T06:32:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiateSuite -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.TC001@23faf8f2]" name="setUp" is-config="true" duration-ms="73545" started-at="2018-10-17T06:32:00Z" finished-at="2018-10-17T06:33:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="runTest()[pri:0, instance:testcases.TC001@23faf8f2]" name="runTest" duration-ms="153" started-at="2018-10-17T06:33:14Z" finished-at="2018-10-17T06:33:14Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.org.excelproject.myexcelproject.DriverScript.m_mainDriver(DriverScript.java:113)
at testcases.TC001.runTest(TC001.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.TC001@23faf8f2]" name="tearDown" is-config="true" duration-ms="5334" started-at="2018-10-17T06:33:14Z" finished-at="2018-10-17T06:33:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.TC001@23faf8f2]" name="setUp" is-config="true" duration-ms="18132" started-at="2018-10-17T06:33:19Z" finished-at="2018-10-17T06:33:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="runTest()[pri:0, instance:testcases.TC001@23faf8f2]" name="runTest" duration-ms="8" started-at="2018-10-17T06:33:38Z" finished-at="2018-10-17T06:33:38Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.org.excelproject.myexcelproject.DriverScript.m_mainDriver(DriverScript.java:113)
at testcases.TC001.runTest(TC001.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.TC001@23faf8f2]" name="tearDown" is-config="true" duration-ms="15552" started-at="2018-10-17T06:33:45Z" finished-at="2018-10-17T06:34:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="closeSuite()[pri:0, instance:testcases.TC001@23faf8f2]" name="closeSuite" is-config="true" duration-ms="1" started-at="2018-10-17T06:34:01Z" finished-at="2018-10-17T06:34:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeSuite -->
      </class> <!-- testcases.TC001 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
